title: Aaditya Said
logo: img/cat-8157889_1280-photoaidcom-cropped.png
description: A highly motivated and detail-oriented data scientist with a strong foundation in statistical analysis, machine learning, and data visualization. Proven ability to extract actionable insights from complex datasets and a passion for solving real-world problems through data-driven approaches.
#show_downloads: true
theme: jekyll-theme-minimal
